export const products = [
  {
    id: 0,
    name: "Customized Reusable Face Mask",
    pic: "customized-reusable-face-mask.png",
    price: 20,
    rate: 5,
    sale: 20,
  },
  {
    id: 1,
    name: "Young Vision Hand Sanitizer",
    pic: "young-vision-hand-sanitizer.png",
    price: 30,
    rate: 3,
    sale: 10,
  },
  {
    id: 2,
    name: "Customized Reusable Face Mask",
    pic: "customized-reusable-face-mask-2.png",
    price: 35,
    rate: 3,
    sale: 25,
  },
  {
    id: 3,
    name: "Customized Reusable Face Mask",
    pic: "customized-reusable-face-mask-3.png",
    price: 15,
    rate: 4,
    sale: 15,
  },
  {
    id: 4,
    name: "Very Medical Hand Sanitizer",
    pic: "very-medical-hand-sanitizer.png",
    price: 35,
    rate: 3,
    sale: 35,
  },
  {
    id: 5,
    name: "Care Plus Medical Gloves",
    pic: "care-plus-medical-gloves.png",
    price: 35,
    rate: 3,
    sale: 15,
  },
  {
    id: 6,
    name: "Customized Reusable Face Mask",
    pic: "customized-reusable-face-mask.png",
    price: 20,
    rate: 5,
    sale: 20,
  },
  {
    id: 7,
    name: "Young Vision Hand Sanitizer",
    pic: "young-vision-hand-sanitizer.png",
    price: 30,
    rate: 3,
    sale: 10,
  },
  {
    id: 8,
    name: "Customized Reusable Face Mask",
    pic: "customized-reusable-face-mask-2.png",
    price: 35,
    rate: 3,
    sale: 25,
  },
  {
    id: 9,
    name: "Customized Reusable Face Mask",
    pic: "customized-reusable-face-mask-3.png",
    price: 15,
    rate: 4,
    sale: 15,
  },
  {
    id: 10,
    name: "Very Medical Hand Sanitizer",
    pic: "very-medical-hand-sanitizer.png",
    price: 35,
    rate: 3,
    sale: 35,
  },
  {
    id: 11,
    name: "Care Plus Medical Gloves",
    pic: "care-plus-medical-gloves.png",
    price: 35,
    rate: 3,
    sale: 15,
  },
];
